### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by muhammad-naderi** [kaknazaveshtakipishi/PermissionEverywhere#6]
Hi, 

as far as I understand, this library is useful when we need a permission from a service, and most of the times when I have services in background I do not have access to a UI context, and I use the application context.

and it is giving me this exception:

```
[java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                               at android.os.Handler.<init>(Handler.java:200)
                                                                               at android.os.Handler.<init>(Handler.java:114)
                                                                               at com.permissioneverywhere.PermissionRequest.enqueue(PermissionRequest.java:61)
                                                                               at com.shygunsys.pocketcyber.locationservice.TLocationManager.updateLocation(TLocationManager.java:153)
                                                                               at com.shygunsys.pocketcyber.locationservice.TLocationManager.reset(TLocationManager.java:348)
                                                                               at com.shygunsys.pocketcyber.syncService.ShygunLocationSyncServicePost.DoSync(ShygunLocationSyncServicePost.java:88)
                                                                               at com.shygunsys.pocketcyber.syncService.TShygunSyncService.doInBackground(TShygunSyncService.java:139)
                                                                               at com.shygunsys.pocketcyber.syncService.TShygunSyncService.doInBackground(TShygunSyncService.java:33)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)]
```

any idea how to resolve it?

**Comment by farruxx** [comment]
@muhammad-naderi in your case, try to use method `call()` instead of `enqueue()`. I have just tested, it works.(Also I have no ideas why it works)

**Comment by muhammad-naderi** [comment]
with the .call() I will have no Notification then!, which is the main reason I'm using this library bro!
or am I missing something ?

--EDIT

Oops my mistake, 
just take a look at the source !
sorry

**Comment by muhammad-naderi** [comment]
Still call is not what I want, I need the enque model working 

if would be the best if you can give it some time, 
as far as I know creating a UI related object (eg notification) may be handled by handlers and ...
you may check this out:
http://stackoverflow.com/questions/3875184/cant-create-handler-inside-thread-that-has-not-called-looper-prepare
